title: Spirits and Tongues
description:

baseurl: ""
url: "https://spiritsandtongues.com"
paginate: 5
permalink: /blog/:year/:title/
paginate_path: /blog/page:num
excerpt_separator: <!--preview-cutoff-->

markdown: kramdown
highligher: rouge
timezone: America/Chicago

kramdown:
  input: GFM

plugins: ['jekyll-paginate']
